### ISSUE TITLE
TypeError: b2a_hex() argument 1 must be string or buffer, not int

### ISSUE THREAD

**Issue by dadittoz** [ehem/kdztools#5]
Hello.

I am trying to get image for [H85010d_00_EEO_GB_OP_0707.kdz](http://csmgdl.lgmobile.com/dn/downloader.dev?fileKey=FW80RVK652A3ADM1062BYNP/H85010d_00_EEO_GB_OP_0707.kdz) file. Unpacking KDZ to DZ works fine with your tool:

```
# unkdz -f H85010d_00_EEO_GB_OP_0707.kdz -x
[+] Extracting all partitions from v2 file!

[+] Extracting H85010d_00.dz to kdzextracted/H85010d_00.dz
[+] Extracting LGUP_c.dll to kdzextracted/LGUP_c.dll
[+] Extracting LGUP_c.dylib to kdzextracted/LGUP_c.dylib
```

But listing files in DZ fails:

```
# undz -f H85010d_00.dz -l
Traceback (most recent call last):
  File "undz", line 937, in <module>
    dztools.main()
  File "undz", line 903, in main
    self.dz_file = UNDZFile(cmd.dzfile)
  File "undz", line 767, in __init__
    self.open(name)
  File "undz", line 472, in open
    dz_file = self.loadHeader(self.dzfile)
  File "undz", line 79, in loadHeader
    print('[!] Error: field "'+key+'" is non-zero ('+b2a_hex(dz_item[key])+')', file=sys.stderr)
TypeError: b2a_hex() argument 1 must be string or buffer, not int
```

**DZFileTools.py** is able to list and unpack entities in this DZ file:

```
# python ../../DZFileTools.py -f H85010d_00.dz -l
[+] DZ Partition List
=========================================
 0 : PrimaryGPT_0.bin (1131 bytes)
 1 : laf_6.bin (21638565 bytes)
 2 : factory_32774.bin (65 bytes)
 3 : rct_44806.bin (65 bytes)
 4 : persist_45190.bin (21624 bytes)
 5 : system_53382.bin (64958655 bytes)
 6 : system_86431.bin (63906261 bytes)
 7 : system_118918.bin (61 bytes)
 8 : system_119427.bin (63579929 bytes)
 9 : system_151686.bin (575 bytes)
10 : system_151967.bin (61 bytes)
11 : system_152476.bin (54979915 bytes)
12 : system_184454.bin (61 bytes)
13 : system_184963.bin (66788049 bytes)
14 : system_217222.bin (575 bytes)
15 : system_217503.bin (61 bytes)
16 : system_218012.bin (51799024 bytes)
17 : system_249990.bin (61 bytes)
18 : system_250499.bin (77203899 bytes)
19 : system_282758.bin (575 bytes)
20 : system_283039.bin (61 bytes)
21 : system_283548.bin (60097763 bytes)
22 : system_315526.bin (61 bytes)
23 : system_316035.bin (54579963 bytes)
24 : system_348294.bin (574 bytes)
25 : system_348575.bin (61 bytes)
26 : system_349084.bin (72807899 bytes)
27 : system_381062.bin (61 bytes)
28 : system_381571.bin (55718675 bytes)
29 : system_413830.bin (61 bytes)
30 : system_414339.bin (65229039 bytes)
31 : system_446598.bin (61 bytes)
32 : system_447107.bin (59365732 bytes)
33 : system_479366.bin (61 bytes)
34 : system_479875.bin (80319581 bytes)
35 : system_512134.bin (61 bytes)
36 : system_512643.bin (63147325 bytes)
37 : system_544902.bin (61 bytes)
38 : system_545411.bin (63791232 bytes)
39 : system_577670.bin (61 bytes)
40 : system_578179.bin (55561390 bytes)
41 : system_610438.bin (61 bytes)
42 : system_610947.bin (65527137 bytes)
43 : system_643206.bin (61 bytes)
44 : system_643715.bin (71642628 bytes)
45 : system_675974.bin (61 bytes)
46 : system_676483.bin (66680141 bytes)
47 : system_708742.bin (61 bytes)
48 : system_709251.bin (58969574 bytes)
49 : system_741510.bin (61 bytes)
50 : system_742019.bin (59257160 bytes)
51 : system_774278.bin (61 bytes)
52 : system_774787.bin (66727144 bytes)
53 : system_807046.bin (61 bytes)
54 : system_807555.bin (65665715 bytes)
55 : system_839814.bin (61 bytes)
56 : system_840323.bin (89986333 bytes)
57 : system_872582.bin (575 bytes)
58 : system_872863.bin (61 bytes)
59 : system_873372.bin (50633710 bytes)
60 : system_905350.bin (61 bytes)
61 : system_905859.bin (55006467 bytes)
62 : system_938118.bin (575 bytes)
63 : system_938399.bin (61 bytes)
64 : system_938908.bin (59457989 bytes)
65 : system_970886.bin (61 bytes)
66 : system_971395.bin (74823944 bytes)
67 : system_1003654.bin (61 bytes)
68 : system_1004163.bin (80270674 bytes)
69 : system_1036422.bin (61 bytes)
70 : system_1036931.bin (52441454 bytes)
71 : system_1069190.bin (64 bytes)
72 : system_1069699.bin (56374623 bytes)
73 : system_1101958.bin (64 bytes)
74 : system_1134726.bin (64 bytes)
75 : system_1167494.bin (62 bytes)
76 : system_1168003.bin (5393217 bytes)
77 : system_1188175.bin (32947348 bytes)
78 : cust_1328262.bin (1151958 bytes)
79 : BackupGPT_7728123.bin (1081 bytes)
80 : PrimaryGPT_0.bin (740 bytes)
81 : xbl_6.bin (1081561 bytes)
82 : xblbak_774.bin (1081561 bytes)
83 : BackupGPT_8187.bin (694 bytes)
84 : PrimaryGPT_0.bin (473 bytes)
85 : xbl2_6.bin (1081561 bytes)
86 : xbl2bak_774.bin (1081561 bytes)
87 : BackupGPT_2043.bin (431 bytes)
88 : PrimaryGPT_0.bin (540 bytes)
89 : BackupGPT_2043.bin (500 bytes)
90 : PrimaryGPT_0.bin (1716 bytes)
91 : boot_6.bin (15664007 bytes)
92 : recovery_10246.bin (16855046 bytes)
93 : recoverybak_20486.bin (16855046 bytes)
94 : tz_30726.bin (460494 bytes)
95 : tzbak_31238.bin (460494 bytes)
96 : aboot_31750.bin (460284 bytes)
97 : abootbak_32262.bin (460284 bytes)
98 : raw_resources_32774.bin (767759 bytes)
99 : raw_resourcesbak_33798.bin (767759 bytes)
100 : rpm_34822.bin (116304 bytes)
101 : rpmbak_34950.bin (116304 bytes)
102 : hyp_35078.bin (90906 bytes)
103 : hypbak_35206.bin (90906 bytes)
104 : pmic_35334.bin (13347 bytes)
105 : pmicbak_35462.bin (13347 bytes)
106 : devcfg_35590.bin (17102 bytes)
107 : devcfgbak_35622.bin (17102 bytes)
108 : modem_35654.bin (38694264 bytes)
109 : sec_57670.bin (291 bytes)
110 : keymaster_57798.bin (98465 bytes)
111 : keymasterbak_57926.bin (98465 bytes)
112 : cmnlib_58054.bin (121613 bytes)
113 : cmnlibbak_58182.bin (121613 bytes)
114 : cmnlib64_58310.bin (137219 bytes)
115 : cmnlib64bak_58438.bin (137219 bytes)
116 : apdp_58566.bin (2873 bytes)
117 : msadp_58694.bin (2876 bytes)
118 : BackupGPT_59387.bin (1668 bytes)
119 : PrimaryGPT_0.bin (524 bytes)
120 : BackupGPT_2043.bin (465 bytes)
121 : PrimaryGPT_0.bin (412 bytes)
122 : BackupGPT_2043.bin (371 bytes)
123 : OP_EEO_GB.img (221903442 bytes)
```

Actually I just wanted to extract system.img from this KDZ. I could use **DZFileTools.py**, but I have no idea how to merge system_*.bin chunks into one file after extraction. Looks like it should be possible with your tool.

**Comment by dadittoz** [comment]
Okay, I've managed to get system_\*.bin files into system.img with **SystemMerger.py**. But the resulting image doesn't look valid:
```
# e2fsck -n system10d.img
e2fsck 1.42.13 (17-May-2015)
Error reading block 1114621 (Attempt to read block from filesystem resulted in short read).  Ignore error? no

system: Attempt to read block from filesystem resulted in short read while reading block 1114621

system: Attempt to read block from filesystem resulted in short read reading journal superblock

e2fsck: Attempt to read block from filesystem resulted in short read while checking ext3 journal for system

system: ********** WARNING: Filesystem still has errors **********
```

**Comment by dadittoz** [comment]
Okay. I finally figured it out :) Had to make a few changes to **undz** in order to work on this particular DZ. I will send you pull requests later. Finally valid system image!

```
$ e2fsck -n system.image
e2fsck 1.42.13 (17-May-2015)
system: clean, 8823/283920 files, 1068856/1134793 blocks
```

**Comment by ehem** [comment]
Sorry, been a while since I checked back here.  Looks like you've _roughly_ got the right idea, though there are some differences on how I'd do it. (still looking through)

**Comment by ehem** [comment]
I'm guessing the H850 is one of the variants of LG's G5?

Having examined the KDZ file you mentioned, they've pretty clearly done rather a lot more than simply making a few fields non-zero.  I'd be very cautious about trusting the results at this point.  Having multiple chunks labeled "PrimaryGPT_0.bin" is **highly** suspicious.

I'm glad I foresaw some of the things they did and provided warnings/error messages to indicate something was up.  The H850 file has the chunks in a scrambled order, this may actually be a flag to LG's tools to write the various areas of the on-board eMMC in a different order than straight from block 0 to block nnn.

This is going to take a while to truly fix.

**Comment by ehem** [comment]
My repository now has _this_ fixed.  Seemed pretty simple to put an interpretation onto one of those newly non-zero fields.  There is still more to do since some of these format changes have problematic implications.  Hopefully easily solved, but timeframe is unknown (particularly if I end up busy elsewhere).
